hashgraph/hedera-cli

- .circleci/config.yml
> Update circleci config to manage release as a separate job in master

- .circleci/config.yml
- scripts/release.sh
Set oss@hedera.com identity for git push invoked in circleci.
> Circleci split release job

- .circleci/config.yml
- scripts/release.sh
CI for automated release manually tested, passes on circleci.
> Remove unnecessary prerequisites

- README.md
> CircleCI Status Badge

- .circleci/config.yml
- LICENSE
- README.md
- build.gradle
- scripts/build.sh
Test coverage file is uploaded to coveralls.io
> Test coverage jacoco

- CONTRIBUTING.md
- src/main/java/com/hedera/cli/shell/CliPromptProvider.java
> Update setup prompt and contributing.md

- src/main/java/com/hedera/cli/hedera/crypto/CryptoTransfer.java
- src/main/java/com/hedera/cli/hedera/crypto/CryptoTransferMultiple.java
- src/main/java/com/hedera/cli/hedera/utils/Utils.java
- src/main/java/com/hedera/cli/models/Recipient.java
- src/main/java/com/hedera/cli/models/Sender.java
- src/main/java/com/hedera/cli/models/TransactionObj.java
> Add preview before crypto transfer, Close #15

- README.md
- install.sh
Simple generic curl installation script for released hedera binaries.
Closes #36
> 36 curl installer

- src/main/java/com/hedera/cli/Initialise.java
- src/main/java/com/hedera/cli/hedera/Hedera.java
- src/main/java/com/hedera/cli/hedera/crypto/AccountDelete.java
- src/main/java/com/hedera/cli/hedera/crypto/AccountList.java
- src/main/java/com/hedera/cli/hedera/crypto/AccountRecovery.java
- src/main/java/com/hedera/cli/hedera/setup/Setup.java
- src/main/java/com/hedera/cli/hedera/utils/AccountUtils.java
- src/main/java/com/hedera/cli/hedera/utils/DataDirectory.java
- src/test/java/com/hedera/cli/hedera/crypto/AccountListTest.java
> Refactor and clean value passed to index.txt. Close #33

- src/main/java/com/hedera/cli/hedera/crypto/AccountList.java
- src/main/java/com/hedera/cli/hedera/setup/Setup.java
- src/main/java/com/hedera/cli/hedera/utils/DataDirectory.java
- src/test/java/com/hedera/cli/hedera/utils/DataDirectoryTest.java
> Fixes account list which shows truncated account

- gradle.properties
> Trigger v0.0.4 to update brewtap

- README.md
> release version badge

- build.gradle
- src/main/java/com/hedera/cli/hedera/botany/BotanyWordListHelper.java
- src/test/java/com/hedera/cli/hedera/botany/AdjectivesWordListHelperTest.java
- src/test/java/com/hedera/cli/hedera/botany/BotanyWordListHelperTest.java
> Specific classes or packages can be excluded because of specific reasons

- src/main/java/com/hedera/cli/services/CurrentAccountService.java
- src/test/java/com/hedera/cli/services/CurrentAccountServiceTest.java
> Simple tests for CurrentAccountService

- .vscode/launch.json
- src/test/java/com/hedera/cli/hedera/crypto/AccountUseTest.java
- src/test/java/com/hedera/cli/hedera/crypto/CryptoTransferMultipleTest.java
> Temporary codacy fixes

- src/main/java/com/hedera/cli/models/DataDirectory.java
- src/test/java/com/hedera/cli/models/DataDirectoryTest.java
- src/test/java/com/hedera/cli/models/PreviewTransferListTest.java
100% test coverage for all models
> 43 tests models

- src/main/java/com/hedera/cli/hedera/crypto/AccountRecovery.java
> Use the client with no preset operator when executing setup

- src/main/java/com/hedera/cli/shell/ShellHelper.java
> No reassignment of params allowed

- gradle.properties
Signed-off-by: Serene Lim <serene@hedera.com>
> Bump version to  0.1.0

- gradle.properties
- src/main/java/com/hedera/cli/hedera/crypto/AccountRecovery.java
> hotfix for NPE during setup command

- gradle.properties
- src/main/java/com/hedera/cli/hedera/crypto/AccountCreate.java
> Fixes NPE in deliberately wrong workflow checked by Cooper. Closes #105

- gradle.properties
Signed-off-by: Serene Lim <serene@hedera.com>
> Bump version 0.1.4

- build.gradle
- src/main/java/com/hedera/cli/hedera/crypto/AccountGetInfo.java
- src/main/java/com/hedera/cli/hedera/crypto/AccountRecovery.java
- src/main/java/com/hedera/cli/hedera/setup/Setup.java
- src/main/java/com/hedera/cli/models/DataDirectory.java
- src/main/java/com/hedera/cli/services/HederaGrpc.java
- src/test/java/com/hedera/cli/hedera/setup/SetupTest.java
- src/test/java/com/hedera/cli/models/AccountInfoSerializerTest.java
> Java sdk081

- src/main/java/com/hedera/cli/hedera/validation/ValidateTransferList.java
- src/test/java/com/hedera/cli/hedera/validation/ValidateTransferListTest.java
Signed-off-by: Serene Lim <serene@hedera.com>
> Fixes cryptotransfer integration test bug

- gradle.properties
Signed-off-by: Serene Lim <serene@hedera.com>
> Bump cli version to 0.1.5

- README.md
> sudo bash is needed for correct installation on linux

- build.gradle
- src/main/java/com/hedera/cli/Application.java
- src/main/java/com/hedera/cli/commands/CommandBase.java
- src/main/java/com/hedera/cli/commands/GetStarted.java
- src/main/java/com/hedera/cli/commands/HederaConsensus.java
- src/main/java/com/hedera/cli/commands/HederaContract.java
- src/main/java/com/hedera/cli/commands/HederaCrypto.java
- src/main/java/com/hedera/cli/commands/HederaFile.java
- src/main/java/com/hedera/cli/commands/HederaMirror.java
- src/main/java/com/hedera/cli/commands/HederaVersion.java
- src/main/java/com/hedera/cli/hedera/network/Network.java
- src/main/java/com/hedera/cli/models/AccountManager.java
- src/main/java/com/hedera/cli/models/DataDirectory.java
- src/main/java/com/hedera/cli/services/CurrentAccountService.java
- src/main/java/com/hedera/cli/services/HederaGrpc.java
- src/main/java/com/hedera/cli/shell/CliPromptProvider.java
- src/test/java/com/hedera/cli/defaults/CommandBaseTest.java
- src/test/java/com/hedera/cli/models/AccountManagerTest.java
- Update sdk version
- Rename CliDefaults to CommandBase
- Simplify isAccountId() function
- Minor changes to annotations, removal of extraneous comments, renames
Signed-off-by: Apekshit Sharma <apekshit.sharma@hedera.com>
> Minor changes

- README.md
Fix the README (broken code snippet markdown) and add a table of contents (TOC).
**Checklist**
> Fix: Docs structure and TOC

- README.md
- Add video to documentation (prototype video)
> Add video to documentation

- __tests__/commands/account/balance.test.ts
Fix missing flag for account balance test.
> Add fix for missing property account balance test

- README.md
Add contribution "feature requests" docs
> Add contribution "feature requests" docs

- src/commands/backup.ts
- src/commands/hbar.ts
- src/utils/display.ts
- src/utils/enquirer.ts
Create `enquirer` utils which closes #191
> Add Enquirer utils - Closes #191

- README.md
- src/commands/script/examples.json
- src/state/base_state.json
- src/state/state.json
The goal of this PR is to host an `examples.json` file which contains multiple useful scripts for users to download into the state of their CLI tool. You can also load the `init` script which downloads the same examples.
Scripts:
```json
{
"scripts": {
"script-token": {
"name": "token",
"commands": [
"network use testnet",
"account create -a random --args privateKey,privKeyAcc1 --args alias,aliasAcc1 --args accountId,idAcc1",
"account create -a random --args privateKey,privKeyAcc2 --args alias,aliasAcc2 --args accountId,idAcc2",
"account create -a random --args privateKey,privKeyAcc3 --args alias,aliasAcc3 --args accountId,idAcc3",
"token create -n mytoken -s MTK -d 2 -i 1000 --supply-type infinite -a {{privKeyAcc1}} -t {{idAcc2}} -k {{privKeyAcc2}} --args …
```
> Add script examples and host them in repo

- README.md
- src/api/account.ts
- src/api/token.ts
- src/commands/setup.ts
- src/utils/account.ts
- src/utils/token.ts
Verify operator balance on setup init and reload commands - Closes #195
> Verify operator balance on setup init and reload commands - Closes #195

- src/commands/token/create.ts
- src/commands/token/createFromFile.ts
- src/utils/hbar.ts
- src/utils/sign.ts
- src/utils/token.ts
Add signing module for individual signing or sign transactions with more complex requirements.
For more complex transactions, a transaction type can be created that lists all the possible signing requirements.
If the right keys are present, the transaction will be signed by these keys. 
Closes: #204
> Add signing module - Closes #204

- README.md
Improvements for the README file
**Related issue(s)**:
-
Fixes #
-
**Notes for reviewer**:
-
**Checklist**
> Improvements for README

- README.md
> Add small docs fixes

- Dockerfile
- README.md
- docker-entrypoint.sh
First part in supporting CI/CD pipelines/GitHub Actions by adding a Dockerfile.
> Add Dockerfile and entrypoint script

- src/utils/state.ts
Fix for: Can't associate with external tokens - Closes #231
**Checklist**
> Add token associations for external tokens - Closes #231

- .github/dependabot.yml
- .gitignore
- Updates the `.gitignore` file definitions.
- Adds a dependabot configuration file.
- Closes #235
> chore: add dependabot configuration and update git ignore

- .pre-commit-config.yaml
- package-lock.json
- package.json
- Updates the software license specified in `package.json` 
- Updates the `pre-commit` configuration file
- Closes #234
> chore: update the license configured in npm and the pre-commit configuration

- .github/CODEOWNERS
- .github/pull_request_template.md
- Adds a pull request template.
- Adds a `CODEOWNERS` definition.
- Closes #243
> chore: add code owner definitions and a pull request template

- .pre-commit-config.yaml
- package-lock.json
- package.json
- Disables husky by removing the dev dependency and the prepare hook from `package.json`
- Updates the `pre-commit` configuration
- Closes #262
> chore: disable husky hooks

- .github/workflows/zxc-code-analysis.yaml
- Updates the Codacy coverage script to use the appropriate language specification. 
- Closes #276
> chore(ci): update Codacy coverage reporting language

- package-lock.json
- package.json
- Add `engine` and `bin` information to install the CLI tool globally.
> fix: Add NPM bin and engine information

- .github/CODEOWNERS
- .github/workflows/flow-deploy-release-artifact.yaml
- .github/workflows/flow-pull-request-formatting.yaml
- .github/workflows/zxc-code-analysis.yaml
- .github/workflows/zxc-compile-code.yaml
Update the self-hosted runner group and the CODEOWNERS file
- Closes #426
> ci: Update self hosted runner group and CODEOWNERS

- .github/workflows/flow-deploy-release-artifact.yaml
- .github/workflows/flow-pull-request-formatting.yaml
- .github/workflows/zxc-code-analysis.yaml
- .github/workflows/zxc-compile-code.yaml
Updates per Q3 audit findings
- Related to #402
> ci: Update per Q3 audit findings

- .github/CODEOWNERS
Update the CODEOWNERS file to replace michielmulders with hashgraph/developer-relations
**Related Issue(s)**:
Fixes Issue #402
> ci: Update codeowners file to add developer-relations team

- package-lock.json
Update the version of the elliptic package to 6.6.1
> chore(deps): Update Elliptic version

- README.md
- src/state/state.json
account delete flags should be optional.
> fix: Change the docs for account delete flags

- README.md
- src/commands/account/delete.ts
- src/commands/account/view.ts
- src/commands/topic/message.ts
- src/utils/dynamicVariables.ts
- src/utils/sign.ts
- Small docs fixes and inconsistencies
- Add prompting feature to account delete when no options provided
- Fix a couple of small bugs for topics
- Update dynamic var docs and add dynamic vars to topics and account view
> feat: Add prompt to account delete, docs fixes, and dynamic var additions

- README.md
- src/state/state.json
- src/utils/dynamicVariables.ts
The old dynamic variable system uses a comma-based notation. We want to improve this to an arrow notation that clearly shows what the output is and what label it gets. 
**Old:** `privateKey,myPrivateKey`
**New:** `privateKey-->myPrivateKey`
> feat: Improve dynamic variable notation system for readability

- README.md
- __tests__/helpers/state.ts
- src/contracts/scripts/balance.js
- src/contracts/scripts/deploy.js
- src/contracts/scripts/mint.js
- src/state/base_state.json
- src/state/config.ts
- src/state/state.json
- src/state/stateController.ts
- types/state.d.ts
Removed memory functions and added functions that read the args object for the active script. This allows you to store arguments from a Hardhat script and reference them in other commands in your script block as dynamic variables.
> feat: Enable communication between Hardhat and other commands in script blocks

- README.md
Small docs update to make it clearer what the convention is for script blocks.
- Closes #515
> feat: Update docs for scripts
